Update INSTALL.md and LOCALIZE.md
maqsoftware/GLEXP-Team-onebillion-Hindi pull request #216
Opened 2019-08-13 07:30 UTC by Shailin

|PR checklist|Status|
|-----|:------:|
|Is issue created in GitHub?|[Yes](https://github.com/maqsoftware/Pehla-Class/issues/215)|
|Is code analysis task executed and issues resolved in the Java/Kotlin code?|NA|
|Is code analysis task executed and issues resolved in the CPP/native code?|NA|
|Is the version code set in the AndroidManifest.xml or build.gradle file to 1 more than the version which has already been published?|NA|
|Is code commenting done properly for the changes made?|NA|
|Is correct variable naming convention followed?|NA|
|Is auto formatting shortcut Ctrl+Alt+Shift+L executed in all files?|NA|
|Are the message strings used in the application taken from strings.xml file?|NA|
|Are the permissions which are not required removed from AndroidManifest.java file?|NA|
|Is the _uses-feature_ tag used for only must have feature in AndroidManifest.java file?|NA|
|Are the generated files correctly configured in .gitignore?|NA|
|Are the release signing configurations removed from the gradle files?|NA|
|Is commented code removed from all files?|NA|
|Are updated images compressed (< 100 KB)?|NA|
|Ensured there are no typos in any string. For example: Variable/method names, hardcoded strings, commit messages, PR titles, issues, code comments?|Yes|

2019-08-13 07:48 UTC, akashdabhi03 requested changes

2019-08-13 07:48 UTC, akashdabhi03 commented on INSTALL-STANDALONE.md
> +3. To change the app locale, just select the desired language from the build variant.
In order to build the app for a specific language, select the desired language from the build variant.

2019-08-13 07:48 UTC, akashdabhi03 commented on INSTALL-STANDALONE.md
> +4. Add google-services.json file in language specific [app](https://github.com/maqsoftware/Pehla-Class/tree/master/app/src) folder. It is there in Firebase console after the app project has been crea
The _google-service.json_ file is available in the Firebase console after a new Android app has been added to a Firebase project.

2019-08-13 07:48 UTC, akashdabhi03 commented on INSTALL-STANDALONE.md
> +		adb install app/english/release/app-english-release.apk
I think the users would select the debug version by default. Hence, we should refer to the debug version folder and APK.

2019-08-13 07:48 UTC, akashdabhi03 commented on INSTALL-STANDALONE.md
> +# Building Pehla Class
We can rename this file to INSTALL.md

2019-08-13 11:16 UTC, alankrutap01 commented on LOCALIZE.md
> +This is defined in the file `community_LOCALE/units.xml`. An example of the first part of the Pehla Class Swahili _learning journey_ from `community_swunits.xml`is shown below. The First unit is an i
Either keep First as in lowercase or keep second in upper case

2019-08-13 11:16 UTC, alankrutap01 commented on LOCALIZE.md
>  2. The time that the subtitle should appear on the screen, followed by `-->` and the time it should disappear.
The time at which the subtitle....

2019-08-19 04:22 UTC, akashdabhi03 submitted a review, later dismissed

2019-08-23 06:08 UTC, ankitk20 requested changes

2019-08-23 06:08 UTC, ankitk20 commented on INSTALL.md
`google-services.json`. Also, the s is missing in one of its name instance.
Update the line to this "..  after registering a new app in Firebase console"

2019-08-23 06:08 UTC, ankitk20 commented on README.md
> +[Installation instructions for Pehla Class English](INSTALL-STANDALONE.md)
Check the reference of INSTALL-STANDALONE.md file

2019-08-27 13:22 UTC, akashdabhi03 approved these changes

2019-08-28 10:39 UTC, ankitk20 approved these changes

2019-08-28 10:39 UTC, merged