Removed unnecessary permissions from Manifest file
maqsoftware/GLEXP-Team-onebillion-Hindi pull request #45
Opened 2019-06-17 11:37 UTC by akashdabhi03

2019-06-20 08:46 UTC, ankitk20 requested changes

2019-06-20 08:46 UTC, ankitk20 commented on app/src/main/AndroidManifest.xml
> +        tools:ignore="GoogleAppIndexingWarning">
Remove ignore warning

2019-06-20 08:46 UTC, ankitk20 commented on app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/MainActivity.java
> +//    public static OBLocationManager locationManager;
Remove this if not required

2019-06-20 08:46 UTC, ankitk20 commented on app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/MainActivity.java
> +//        return micPermission;
Remove commented code

2019-06-20 08:46 UTC, ankitk20 commented on app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/MainActivity.java
> +//        locationManager = new OBLocationManager(this);
Remove this

2019-06-20 08:46 UTC, ankitk20 commented on app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/SplashScreenActivity.java
> +                }, 3500);
Toast.LENGTH_LONG

2019-06-20 08:46 UTC, ankitk20 commented on app/src/main/java/com/maq/xprize/onecourse/hindi/utils/OBAnalyticsManagerCommunity.java
> +//        Location loc = OBLocationManager.sharedManager.getLastKnownLocation();
Remove commented code from everywhere

2019-06-20 09:08 UTC, akashdabhi03 commented on app/src/main/AndroidManifest.xml
> +        tools:ignore="GoogleAppIndexingWarning">
Correct

2019-06-20 09:10 UTC, akashdabhi03 commented on app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/SplashScreenActivity.java
> +                }, 3500);
Updated

2019-06-20 09:37 UTC, akashdabhi03 commented on app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/MainActivity.java
> +//    public static OBLocationManager locationManager;
Removed

2019-06-20 09:45 UTC, Shailin submitted a review, later dismissed

2019-06-20 09:47 UTC, ankitk20 submitted a review, later dismissed

2019-06-20 12:00 UTC, Shailin submitted a review, later dismissed

2019-06-21 06:10 UTC, mathewnik90 approved these changes

2019-06-21 06:13 UTC, merged