Updated OBB extraction logic to handle updates
maqsoftware/GLEXP-Team-onebillion-Hindi pull request #6
Opened 2019-05-30 11:29 UTC by akashdabhi03

2019-05-30 12:49 UTC, ankitk20 submitted a review, later dismissed

2019-06-06 13:34 UTC, mathewnik90 requested changes

2019-06-06 13:34 UTC, mathewnik90 commented on app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/SplashScreenActivity.java
> +            sharedPref = getSharedPreferences("ExpansionFile", MODE_PRIVATE);
Create a common method and call

2019-06-06 13:35 UTC, mathewnik90 approved these changes

2019-06-06 13:35 UTC, merged