Text-to-speech implementation
maqsoftware/GLEXP-Team-onebillion-Hindi pull request #72
Opened 2019-06-20 10:29 UTC by harshsiloiya98

2019-06-27 13:15 UTC, akashdabhi03 requested changes

2019-06-27 13:15 UTC, akashdabhi03 commented on app/src/main/java/com/maq/xprize/onecourse/hindi/utils/OBConfigManager.java
> +        setValue("extensions_text", "txt");
Use EXTENSIONS_TEXT

2019-06-27 13:15 UTC, akashdabhi03 commented on app/src/main/java/com/maq/xprize/onecourse/hindi/utils/OBAudioManager.java
> +            String txt_suffix = OBConfigManager.sharedManager.getTextExtensions().get(0);
Camel case

2019-07-05 04:46 UTC, akashdabhi03 submitted a review, later dismissed

2019-07-05 13:33 UTC, akashdabhi03 approved these changes

2019-07-05 18:14 UTC, mathewnik90 commented on app/src/main/java/com/maq/xprize/onecourse/hindi/controls/OBPresenter.java
> +                    Callable<Void> c2 = new Callable<Void>() {
Use better names.
audioPlayer and animator?

2019-07-05 18:14 UTC, mathewnik90 approved these changes

2019-07-05 18:14 UTC, merged