Fixed UI issue related to cropping of keyboard and overlapping of keyboard with text box
maqsoftware/GLEXP-Team-onebillion-Hindi pull request #73
Opened 2019-06-20 10:55 UTC by piyushonkar

Fixed #68

2019-06-20 12:20 UTC, akashdabhi03 requested changes

2019-06-20 12:20 UTC, akashdabhi03 commented on app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/oc_playzone/OC_PlayZoneTypewrite.java
> +        float textBottom = objectDict.get("keyboard_rect").frame.top;
frame().top

2019-06-20 12:20 UTC, akashdabhi03 commented on app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/oc_playzone/OC_PlayZoneTypewrite.java
> +        WindowManager wm = (WindowManager) activity.getSystemService(Context.WINDOW_SERVICE);
Use a better variable name

2019-06-20 12:20 UTC, akashdabhi03 commented on app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/oc_playzone/OC_PlayZoneTypewrite.java
> +        Point size = new Point();
Even for this

2019-06-20 12:20 UTC, akashdabhi03 commented on app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/oc_playzone/OC_PlayZoneTypewrite.java
> +        if(screenHeight - 20f < keyboardRect.frame.bottom )
Can we avoid hard-coding of values?

2019-06-21 06:16 UTC, piyushonkar commented on app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/oc_playzone/OC_PlayZoneTypewrite.java
> +        WindowManager wm = (WindowManager) activity.getSystemService(Context.WINDOW_SERVICE);
Done

2019-06-21 06:16 UTC, piyushonkar commented on app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/oc_playzone/OC_PlayZoneTypewrite.java
> +        if(screenHeight - 20f < keyboardRect.frame.bottom )
Done

2019-06-21 06:16 UTC, piyushonkar commented on app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/oc_playzone/OC_PlayZoneTypewrite.java
> +        Point size = new Point();
Done.

2019-06-21 06:16 UTC, akashdabhi03 approved these changes

2019-06-21 06:40 UTC, mathewnik90 commented on app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/oc_playzone/OC_PlayZoneTypewrite.java
> +        // Check for bottom of keyboard not exceeding screen size, if it exceeds then set bottom of keyboard
Check if bottom of keyboard exceeds screen size, if it does then set bottom

2019-06-21 06:46 UTC, merged